plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlinx.serialization)
    alias(libs.plugins.compose.multiplatform)
    alias(libs.plugins.kotlin.compose)
}

val generateAppVersion by tasks.registering {
    val version = libs.versions.appVersion.get()
    val outputDir = layout.buildDirectory.dir("generated/version/kotlin")
    inputs.property("version", version)
    outputs.dir(outputDir)
    doLast {
        val file = outputDir.get().file("app/what/domain/constants/AppVersion.kt").asFile
        file.parentFile.mkdirs()
        file.writeText(
            """
            // Generated by Gradle task generateAppVersion from libs.versions.toml. DO NOT EDIT.
            package app.what.domain.constants

            internal const val GENERATED_VERSION_NAME = "$version"
            """.trimIndent()
        )
    }
}

kotlin {
    jvmToolchain(21)

    jvm()
    androidTarget {
        publishLibraryVariants("release")
    }
    iosX64()
    iosArm64()
    iosSimulatorArm64()
    @OptIn(org.jetbrains.kotlin.gradle.ExperimentalWasmDsl::class)
    wasmJs {
        browser()
    }

    sourceSets {
        commonMain {
            kotlin.srcDir(generateAppVersion)
            dependencies {
                api(libs.foundation.navigation)
                api(libs.foundation.updater)
                implementation(libs.kotlinx.serialization.json)
                implementation(libs.kotlinx.datetime)
                implementation(libs.koin.core)
                implementation(compose.ui)
            }
        }
        commonTest.dependencies {
            implementation(kotlin("test"))
        }
    }
}

android {
    namespace = "app.what.domain"
    compileSdk = 36

    defaultConfig {
        minSdk = 26
    }
}
