plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlinx.serialization)
    alias(libs.plugins.compose.multiplatform)
    alias(libs.plugins.kotlin.compose)
}

val generatedVersionDir = layout.buildDirectory.dir("generated/source/appVersion/commonMain")

val generateAppVersionTask = tasks.register("generateAppVersion") {
    val version = libs.versions.appVersion.get()
    inputs.property("version", version)
    outputs.dir(generatedVersionDir)
    doLast {
        val file = generatedVersionDir.get().file("app/what/foundation/constants/AppVersion.kt").asFile
        file.parentFile.mkdirs()
        file.writeText(
            """
            // Generated by Gradle task :core:foundation:generateAppVersion. Do not edit.
            package app.what.foundation.constants

            internal const val APP_BUILD_VERSION_NAME = "$version"
            """.trimIndent() + "\n"
        )
    }
}

tasks.matching { it.name.startsWith("compile") || it.name == "preBuild" || it.name.contains("prepareKotlinIdeaImport", ignoreCase = true) }.configureEach {
    dependsOn(generateAppVersionTask)
}

kotlin {
    jvmToolchain(21)

    jvm()
    androidTarget {
        publishLibraryVariants("release")
    }
    iosX64()
    iosArm64()
    iosSimulatorArm64()
    @OptIn(org.jetbrains.kotlin.gradle.ExperimentalWasmDsl::class)
    wasmJs {
        browser()
    }

    sourceSets {
        commonMain {
            kotlin.srcDir(generateAppVersionTask)
            dependencies {
            implementation(compose.runtime)
            implementation(compose.foundation)
            implementation(compose.material3)
            implementation(compose.ui)
            implementation(compose.materialIconsExtended)
            implementation(compose.components.resources)

            api(libs.kotlinx.datetime)
            api(libs.jetbrains.lifecycle.viewmodel)
            api(libs.jetbrains.lifecycle.viewmodel.compose)
            api(libs.jetbrains.lifecycle.runtime.compose)
            implementation(libs.kotlinx.serialization.json)
            implementation(libs.materialKolor)
            implementation(libs.bundles.coil)
            implementation(libs.koin.core)
            implementation(libs.koin.compose)
            implementation(libs.bundles.ktor)
            }
        }
        androidMain.dependencies {
            implementation(libs.androidx.core.ktx)
            implementation(libs.androidx.activity.compose)
            implementation(project.dependencies.platform(libs.firebase.bom))
            implementation(libs.firebase.analytics)
            implementation(libs.firebase.crashlytics)
            implementation(project.dependencies.platform(libs.bom))
            implementation(libs.appupdate)
            implementation(libs.process.phoenix)
        }
        commonTest.dependencies {
            implementation(kotlin("test"))
        }
    }
}

android {
    namespace = "app.what.foundation"
    compileSdk = 36

    defaultConfig {
        minSdk = 26
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }
}

compose.resources {
    packageOfResClass = "app.what.foundation.generated.resources"
}